version: "3.1"
services:
    mongodb:
      image: mongo:latest
      volumes:
        - ./docker/mongo/entrypoint:/docker-entrypoint-initdb.d
        - mongodb:/data/db
      oom_kill_disable: true
      environment:
        - MONGO_INITDB_DATABASE=airbnb
      ports:
        - 27017:27017

volumes:
  mongodb:

